export const mutation_types = {
  ADD_NEW_TODO: "ADD_NEW_TODO",
  DELETE_TODO: "DELETE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  SELECT_TODO: "SELECT_TODO",
  SET_TODOS: "SET_TODOS",
  SET_DONE_TODOS: "SET_DONE_TODOS",
  SET_NOT_DONE_TODOS: "SET_NOT_DONE_TODOS",
  SET_TODOS_BY_FILTER: "SET_TODOS_BY_FILTER",
  EDIT_TODO: "EDIT_TODO",
};
